### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by roberbnd** [kevinhwang91/rnvimr#4] opened 2020-02-15 22:29 UTC
I was thinking in show you a video about the error I mentioned in reddit but I don't what happened I get this error my ranger works in the terminal, this error is when I run :RnvimrToggle
![image](https://user-images.githubusercontent.com/4907027/74596087-1a599a00-5010-11ea-87ba-16e2c6807ac4.png)

**Comment by roberbnd** [comment] 2020-02-15 23:44
Ignore, the error it was because I had 2 nvim instances with the same --listen /tmp/abc
anyway here is the video
https://www.youtube.com/watch?v=-VfteUnJ4tU

**Comment by kevinhwang91** [comment] 2020-02-16 03:32
Run `:RnvimrToggle` and then invoke `eval os.getenv('EDITOR')` in ranger, what the msg the console output?

**Comment by roberbnd** [comment] 2020-02-16 04:15
after run eval os.getenv('EDITOR') I got:
![image](https://user-images.githubusercontent.com/4907027/74598961-9370e580-5040-11ea-99a5-8c36c69a301f.png)

ranger-1.9.3.4
NVIM v0.4.3

**Comment by roberbnd** [comment] 2020-02-16 04:24
I could make it works using:
export VISUAL= ~/.config/nvim/plugged/rnvimr/bin/editor.py
 before to start nvim

**Comment by kevinhwang91** [comment] 2020-02-16 04:34
The issue is caused by VISUAL, I will fix it soon.

You can work fine by `unset VISUAL`.

**Comment by roberbnd** [comment] 2020-02-16 04:38
oh! yeah! nice,  using `unset VISUAL` works perfectly, Thanks!

**Comment by kevinhwang91** [comment] 2020-02-16 04:42
I have committed the patch, please update the plugin. 

Close this issue if everything works fine.

**Closed** 2020-02-16 04:53 UTC
